// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaq3HTurHJ7zdMqq4Q64ubY6x3NBcUXIk',
    appId: '1:352696704188:web:362da652f8fd67e43684b9',
    messagingSenderId: '352696704188',
    projectId: 'wafflereservation',
    authDomain: 'wafflereservation.firebaseapp.com',
    storageBucket: 'wafflereservation.appspot.com',
    measurementId: 'G-LNCLDK742D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiHVWyMtnMgpup4hmCmTesv_8_OMf7n0I',
    appId: '1:352696704188:android:e372847a1ddcaf753684b9',
    messagingSenderId: '352696704188',
    projectId: 'wafflereservation',
    storageBucket: 'wafflereservation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBUXMqjs3S-AhQr7vT5IS3vzU64gFkplk',
    appId: '1:352696704188:ios:6ccae5af8163d7ea3684b9',
    messagingSenderId: '352696704188',
    projectId: 'wafflereservation',
    storageBucket: 'wafflereservation.appspot.com',
    iosClientId: '352696704188-kre9g0247uqfhuim189cvghaqj7r3k5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
